version: '3.8'

services:
  # Backend API
  backend-api:
    build:
      context: .
      dockerfile: backend-api.Dockerfile
    container_name: turistar-backend-api
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
      - EC2_PUBLIC_IP=${EC2_PUBLIC_IP}
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - mongodb
    networks:
      - turistar-network
    restart: unless-stopped

  # Frontend Next.js
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: turistar-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://backend-api:8000/api/}
    depends_on:
      - backend-api
    networks:
      - turistar-network
    restart: unless-stopped

  # Mobile Development Server
  mobile-dev:
    build:
      context: .
      dockerfile: mobile.Dockerfile
    container_name: turistar-mobile-dev
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    volumes:
      - ./apps/mobile:/app/apps/mobile
      - /app/apps/mobile/node_modules
    networks:
      - turistar-network
    restart: unless-stopped

networks:
  turistar-network:
    driver: bridge