services:
  backend-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-api
    restart: unless-stopped
    ports:
      - "${PORT:-8000}:8000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=${PORT:-8000}
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    networks:
      - app-network
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
