import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F2F2F7',
        alignItems: 'center',
        paddingTop: 40,
    },
    avatarContainer: {
        alignItems: 'center',
        marginBottom: 30,
    },
    avatarCircle: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: '#007AFF',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 10,
    },
    name: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1C1C1E',
        marginBottom: 4,
    },
    role: {
        fontSize: 16,
        color: '#8E8E93',
        marginBottom: 10,
    },
    infoContainer: {
        width: '90%',
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 5,
    },
    infoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 24,
    },
    infoText: {
        fontSize: 16,
        color: '#1C1C1E',
        marginLeft: 12,
    },
    errorText: {
        fontSize: 18,
        color: 'red',
        marginTop: 40,
    },
    btnLogout: {
        backgroundColor: '#FF0000',
        flex: 1,
        padding: 12,
        borderRadius: 8,
        marginRight: 4,
    },
    input: {
        flex: 1,
        fontSize: 16,
        color: '#1C1C1E',
        backgroundColor: '#F2F2F7',
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: 6,
        marginLeft: 12,
        borderWidth: 1,
        borderColor: '#E5E5EA',
    },
    btnSave: {
        backgroundColor: '#007AFF',
        borderRadius: 8,
        padding: 12,
        flex: 1,
        marginLeft: 4,
    },
    btnEdit: {
        backgroundColor: '#5856D6',
        borderRadius: 8,
        padding: 12,
        flex: 1,
        marginLeft: 4,
    },
    pickerContainer: {
        flex: 1,
        marginLeft: 12,
        backgroundColor: '#F2F2F7',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#E5E5EA',
    },
    picker: {
        height: 54,
        width: '100%',
    },
    dangerZoneContainer: {
        marginTop: 40,
        width: '90%',
        alignItems: 'center',
        backgroundColor: '#fff0f0',
        borderRadius: 12,
        padding: 20,
        borderWidth: 1,
        borderColor: '#FF3B30',
    },
    dangerZoneTitle: {
        color: '#FF3B30',
        fontWeight: 'bold',
        fontSize: 16,
        marginBottom: 10,
    },
    btnDelete: {
        backgroundColor: '#FF3B30',
        borderRadius: 8,
        paddingVertical: 12,
        paddingHorizontal: 30,
        marginTop: 10,
    },
    btnDeleteText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
});